apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{.Release.Namespace}}
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres
